---
- name: add unicorn-nginx.conf
  template: src=unicorn.conf.j2 dest=/etc/nginx/conf.d/unicorn.conf

- name: add app directory
  file: path=/var/www/app state=directory

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  notify: restart nginx
